The MapFilters Colab generates state and country lists used in the top filters.

Related page: https://model.earth/data-commons/docs/data

DONE: Reduce state_ids_data object to just state number 01 instead of geoId/01 - Alexandra

You can send output to Github, or copy the resulting file by clicking the folder icon in the left side.

# Installations and Imports

In [ ]:
pip install datacommons_pandas

Collecting datacommons_pandas
  Downloading datacommons_pandas-0.0.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from datacommons_pandas) (1.16.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datacommons_pandas) (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas->datacommons_pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datacommons_pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datacommons_pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datacommons_pandas) (2024.1)
Downloading datacommons_pandas-0.0.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 1.7 MB/s eta 0:00:00
Installing collected packages: datacommons_pandas
Successfully installed datacommons_pandas-0.0.3

In [ ]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)
import datacommons_pandas as dc
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import requests

# Data Pull for all the states in the USA

In [ ]:
stateDict = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California", "CO": "Colorado",
    "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii", "ID": "Idaho",
    "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana",
    "ME": "Maine", "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey",
    "NM": "New Mexico", "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina", "SD": "South Dakota",
    "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
    "DC": "District of Columbia",
    # US Territories
    "AS": "American Samoa", "GU": "Guam", "MP": "Northern Mariana Islands", "PR": "Puerto Rico", "VI": "Virgin Islands of the U.S."
}

stateData = pd.DataFrame(list(stateDict.items()),columns = ['State','StateName'])
stateData.head()

  State   StateName
0    AL     Alabama
1    AK      Alaska
2    AZ     Arizona
3    AR    Arkansas
4    CA  California

In [ ]:
def get_state_ids():
  # Getting the states  dcids
  state_dcids = dc.get_places_in(['country/USA'], 'State')
  # Getting the names of the states
  state_names = [dc.get_property_values([name], 'name') for name in state_dcids['country/USA']]

  data = {}
  for entry in state_names:
      for k,v in entry.items():
          data[k] = v[0]

  # Adding Rest 4 US Territories
  for k,v in dc.get_property_values(['geoId/60','geoId/66','geoId/69','geoId/78'], 'name').items():
      data[k] = v[0]
  return data

In [ ]:
def get_state_ids():
  # Getting the states  dcids
  state_dcids = dc.get_places_in(['country/USA'], 'State')
  # Getting the names of the states
  state_names = [dc.get_property_values([name], 'name') for name in state_dcids['country/USA']]

  data = {}
  for entry in state_names:
      for k,v in entry.items():
          state_number = k.split('/')[-1]
          data[state_number] = v[0]

  # Adding Rest 4 US Territories
  for k,v in dc.get_property_values(['geoId/60','geoId/66','geoId/69','geoId/78'], 'name').items():
      state_number = k.split('/')[-1]
      data[state_number] = v[0]
  return data

In [ ]:
state_ids_data = get_state_ids()
state_ids_data

{'01': 'Alabama',
 '02': 'Alaska',
 '04': 'Arizona',
 '05': 'Arkansas',
 '06': 'California',
 '08': 'Colorado',
 '09': 'Connecticut',
 '10': 'Delaware',
 '11': 'District of Columbia',
 '12': 'Florida',
 '13': 'Georgia',
 '15': 'Hawaii',
 '16': 'Idaho',
 '17': 'Illinois',
 '18': 'Indiana',
 '19': 'Iowa',
 '20': 'Kansas',
 '21': 'Kentucky',
 '22': 'Louisiana',
 '23': 'Maine',
 '24': 'Maryland',
 '25': 'Massachusetts',
 '26': 'Michigan',
 '27': 'Minnesota',
 '28': 'Mississippi',
 '29': 'Missouri',
 '30': 'Montana',
 '31': 'Nebraska',
 '32': 'Nevada',
 '33': 'New Hampshire',
 '34': 'New Jersey',
 '35': 'New Mexico',
 '36': 'New York',
 '37': 'North Carolina',
 '38': 'North Dakota',
 '39': 'Ohio',
 '40': 'Oklahoma',
 '41': 'Oregon',
 '42': 'Pennsylvania',
 '44': 'Rhode Island',
 '45': 'South Carolina',
 '46': 'South Dakota',
 '47': 'Tennessee',
 '48': 'Texas',
 '49': 'Utah',
 '50': 'Vermont',
 '51': 'Virginia',
 '53': 'Washington',
 '54': 'West Virginia',
 '55': 'Wisconsin',
 '56': 'Wyoming',
 '72': 'Puerto Rico',
 '60': 'American Samoa',
 '66': 'Guam',
 '69': 'Northern Mariana Islands',
 '78': 'Virgin Islands of the U.S.'}

In [ ]:
# CO2 = Annual_Emissions_CarbonDioxide_NonBiogenic -- State
# Methane = Annual_Emissions_Methane_NonBiogenic -- State
# Population = Count_Person -- State

def fetch_timelines_data():
  # Getting DCIDs for all the states
  state_ids_data = get_state_ids()
  # Getting the timelines data
  timelines_data = {}
  for key,value in state_ids_data.items():
    try:
      timelines_data[value] = {'Population':round(dc.get_stat_all([key], ['Count_Person'])[key]['Count_Person']['sourceSeries'][0]['val']['2022'],2)}
    except:
      timelines_data[value] = {'Population':0.00}
    try:
      timelines_data[value].update({'CO2':round(dc.get_stat_all([key], ['Annual_Emissions_CarbonDioxide_NonBiogenic'])[key]['Annual_Emissions_CarbonDioxide_NonBiogenic']['sourceSeries'][0]['val']['2021'],2)})
    except:
      timelines_data[value].update({'CO2':0.00})
    try:
      timelines_data[value].update({'Methane':round(dc.get_stat_all([key], ['Annual_Emissions_Methane_NonBiogenic'])[key]['Annual_Emissions_Methane_NonBiogenic']['sourceSeries'][0]['val']['2021'],2)})
    except:
      timelines_data[value].update({'Methane':0.00})

  # Creating the dataframe
  normalized_data = []
  for state, values in timelines_data.items():
      entry = {'StateName': state}
      entry.update(values)
      normalized_data.append(entry)
  dataframe = pd.DataFrame(normalized_data)

  # Adding state abbreviations to the dataframe
  dataframe = stateData.merge(dataframe,how = 'inner',on='StateName')

  # Dividing the data by 1000 and rounding to 2 decimals
  # for col in dataframe.iloc[:,2:]:
  #     dataframe[col] = round(dataframe[col]/1000,2)

  return dataframe

In [ ]:
timelines_df = fetch_timelines_data()
timelines_df.head()

  State   StateName  Population  CO2  Methane
0    AL     Alabama        0.00 0.00     0.00
1    AK      Alaska        0.00 0.00     0.00
2    AZ     Arizona        0.00 0.00     0.00
3    AR    Arkansas        0.00 0.00     0.00
4    CA  California        0.00 0.00     0.00

In [ ]:
# Fetching the data for land area of the states
area_data = gpd.read_file(f'https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_state_500k.zip')
area_data["SqMiles"] = round(area_data['ALAND']/ 2589988.110336,2)
area_data.head()

,STATEFP,STATENS,GEOIDFQ,GEOID,STUSPS,NAME,LSAD,ALAND,AWATER,geometry,SqMiles
0,35,00897535,0400000US35,35,NM,New Mexico,00,314198587197,726463919,"POLYGON ((-109.05017 31.48000, -109.04984 31.4...",121312.75
1,46,01785534,0400000US46,46,SD,South Dakota,00,196341525171,3387709166,"POLYGON ((-104.05788 44.99761, -104.05078 44.9...",75807.89
2,06,01779778,0400000US06,06,CA,California,00,403673296401,20291770234,"MULTIPOLYGON (((-118.60442 33.47855, -118.5987...",155859.13
3,21,01779786,0400000US21,21,KY,Kentucky,00,102266598312,2384223544,"MULTIPOLYGON (((-89.40565 36.52817, -89.39869 ...",39485.35
4,01,01779775,0400000US01,01,AL,Alabama,00,131185049346,4582326383,"MULTIPOLYGON (((-88.05338 30.50699, -88.05109 ...",50650.83

In [ ]:
timelines_df = timelines_df.merge(area_data[['STUSPS','SqMiles']], how='inner', left_on='State', right_on='STUSPS')
timelines_df.drop(columns = ['STUSPS'],inplace=True)
timelines_df

   State                   StateName  Population  CO2  Methane   SqMiles
0     AL                     Alabama        0.00 0.00     0.00  50650.83
1     AK                      Alaska        0.00 0.00     0.00 571051.62
2     AZ                     Arizona        0.00 0.00     0.00 113655.39
3     AR                    Arkansas        0.00 0.00     0.00  51992.70
4     CA                  California        0.00 0.00     0.00 155859.13
5     CO                    Colorado        0.00 0.00     0.00 103637.06
6     CT                 Connecticut        0.00 0.00     0.00   4842.40
7     DE                    Delaware        0.00 0.00     0.00   1948.54
8     FL                     Florida        0.00 0.00     0.00  53654.21
9     GA                     Georgia        0.00 0.00     0.00  57716.60
10    HI                      Hawaii        0.00 0.00     0.00   6422.59
11    ID                       Idaho        0.00 0.00     0.00  82645.12
12    IL                    Illinois        0.00 0.00     0.00  55513.14
13    IN                     Indiana        0.00 0.00     0.00  35825.11
14    IA                        Iowa        0.00 0.00     0.00  55853.26
15    KS                      Kansas        0.00 0.00     0.00  81758.59
16    KY                    Kentucky        0.00 0.00     0.00  39485.35
17    LA                   Louisiana        0.00 0.00     0.00  43216.59
18    ME                       Maine        0.00 0.00     0.00  30845.04
19    MD                    Maryland        0.00 0.00     0.00   9711.14
20    MA               Massachusetts        0.00 0.00     0.00   7800.94
21    MI                    Michigan        0.00 0.00     0.00  56610.28
22    MN                   Minnesota        0.00 0.00     0.00  79631.47
23    MS                 Mississippi        0.00 0.00     0.00  46924.36
24    MO                    Missouri        0.00 0.00     0.00  68746.36
25    MT                     Montana        0.00 0.00     0.00 145550.16
26    NE                    Nebraska        0.00 0.00     0.00  76814.87
27    NV                      Nevada        0.00 0.00     0.00 109860.37
28    NH               New Hampshire        0.00 0.00     0.00   8953.76
29    NJ                  New Jersey        0.00 0.00     0.00   7354.93
30    NM                  New Mexico        0.00 0.00     0.00 121312.75
31    NY                    New York        0.00 0.00     0.00  47123.41
32    NC              North Carolina        0.00 0.00     0.00  48624.12
33    ND                North Dakota        0.00 0.00     0.00  68994.27
34    OH                        Ohio        0.00 0.00     0.00  40858.81
35    OK                    Oklahoma        0.00 0.00     0.00  68596.64
36    OR                      Oregon        0.00 0.00     0.00  95996.74
37    PA                Pennsylvania        0.00 0.00     0.00  44742.23
38    RI                Rhode Island        0.00 0.00     0.00   1033.89
39    SC              South Carolina        0.00 0.00     0.00  30064.23
40    SD                South Dakota        0.00 0.00     0.00  75807.89
41    TN                   Tennessee        0.00 0.00     0.00  41232.74
42    TX                       Texas        0.00 0.00     0.00 261270.02
43    UT                        Utah        0.00 0.00     0.00  82595.69
44    VT                     Vermont        0.00 0.00     0.00   9217.26
45    VA                    Virginia        0.00 0.00     0.00  39482.10
46    WA                  Washington        0.00 0.00     0.00  66455.43
47    WV               West Virginia        0.00 0.00     0.00  24041.23
48    WI                   Wisconsin        0.00 0.00     0.00  54167.29
49    WY                     Wyoming        0.00 0.00     0.00  97088.54
50    DC        District of Columbia        0.00 0.00     0.00     61.13
51    AS              American Samoa        0.00 0.00     0.00     76.36
52    GU                        Guam        0.00 0.00     0.00    209.87
53    MP    Northern Mariana Islands        0.00 0.00     0.00    182.35
54    PR                 Puerto Rico        0.00 0.00     0.00   3424.35
55    VI  Virgin Islands of the U.S.        0.00 0.00     0.00    134.37

In [ ]:
# Converting to a CSV file
timelines_df.to_csv('UN_Timelines_Data.csv', index=False)

## Push CSV to Github

In [ ]:
!apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.

In [ ]:
from google.colab import userdata

In [ ]:
#user information
token = userdata.get('Githubtoken')
USERNAME = "ultracatx"
REPO_NAME = "data-commons-me"
EMAIL = "ivyzhou752@gmail.com"

repo_url = f"https://{token}@github.com/{USERNAME}/{REPO_NAME}.git"

In [ ]:
#config git global user information
!git config --global user.email {EMAIL}
!git config --global user.name {USERNAME}

In [ ]:
#clone repo to local
!git clone {repo_url}

Cloning into 'data-commons-me'...
remote: Enumerating objects: 645, done.
remote: Counting objects: 100% (257/257), done.
remote: Compressing objects: 100% (154/154), done.
remote: Total 645 (delta 152), reused 169 (delta 85), pack-reused 388 (from 1)
Receiving objects: 100% (645/645), 11.26 MiB | 12.45 MiB/s, done.
Resolving deltas: 100% (228/228), done.

In [ ]:
#move csv from /content to repo
!mv UN_Timelines_Data.csv data-commons-me/docs/data

In [ ]:
%cd /content/data-commons-me/docs/data

/content/data-commons-me/docs/data

In [ ]:
!git add UN_Timelines_Data.csv

In [ ]:
!git commit -m "push csv to repo"

[main d738a91] test
 1 file changed, 57 deletions(-)
 delete mode 100644 docs/data/UN_Timelines_Data.csv

In [ ]:
!git push {repo_url}

Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 383 bytes | 383.00 KiB/s, done.
Total 4 (delta 2), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/Ultracatx/data-commons-me.git
To https://github.com/ultracatx/data-commons-me.git
   a66375a..d738a91  main -> main

# Data Pull for all the countries

In [ ]:
!pip install pycountry
import pycountry

Collecting pycountry
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 37.4 MB/s eta 0:00:00
Installing collected packages: pycountry
Successfully installed pycountry-24.6.1

In [ ]:
def get_country_ids():
    country_dcids = dc.get_places_in(['Earth'], 'Country')
    country_names = {dcid: dc.get_property_values([dcid], 'name')[dcid][0] for dcid in country_dcids['Earth']}
    return country_names

country_ids_data = get_country_ids()
country_ids_data

{'country/ABW': 'Aruba',
 'country/AFG': 'Afghanistan',
 'country/AGO': 'Angola',
 'country/AIA': 'Anguilla',
 'country/ALA': 'Åland Islands',
 'country/ALB': 'Albania',
 'country/AND': 'Andorra',
 'country/ANT': 'Netherlands Antilles',
 'country/ARE': 'United Arab Emirates',
 'country/ARG': 'Argentina',
 'country/ARM': 'Armenia',
 'country/ASM': 'American Samoa',
 'country/ATA': 'Antarctica',
 'country/ATB': 'British Antarctic Territory',
 'country/ATF': 'French Southern Territories',
 'country/ATG': 'Antigua and Barbuda',
 'country/ATN': 'Dronning Maud Land',
 'country/AUS': 'Australia',
 'country/AUT': 'Austria',
 'country/AZE': 'Azerbaijan',
 'country/BDI': 'Burundi',
 'country/BEL': 'Belgium',
 'country/BEN': 'Benin',
 'country/BES': 'Bonaire, Sint Eustatius and Saba',
 'country/BFA': 'Burkina Faso',
 'country/BGD': 'Bangladesh',
 'country/BGR': 'Bulgaria',
 'country/BHR': 'Bahrain',
 'country/BHS': 'Bahamas',
 'country/BIH': 'Bosnia and Herzegovina',
 'country/BLM': 'Saint Barthélemy',
 'country/BLR': 'Belarus',
 'country/BLZ': 'Belize',
 'country/BMU': 'Bermuda',
 'country/BOL': 'Bolivia',
 'country/BRA': 'Brazil',
 'country/BRB': 'Barbados',
 'country/BRN': 'Brunei',
 'country/BTN': 'Bhutan',
 'country/BVT': 'Bouvet Island',
 'country/BWA': 'Botswana',
 'country/CAF': 'Central African Republic',
 'country/CAN': 'Canada',
 'country/CCK': 'Cocos (Keeling) Islands',
 'country/CHE': 'Switzerland',
 'country/CHL': 'Chile',
 'country/CHN': 'China',
 'country/CIV': "Côte d'Ivoire",
 'country/CMR': 'Cameroon',
 'country/COD': 'Congo [DRC]',
 'country/COG': 'Congo [Republic]',
 'country/COK': 'Cook Islands',
 'country/COL': 'Colombia',
 'country/COM': 'Comoros',
 'country/CPV': 'Cape Verde',
 'country/CRI': 'Costa Rica',
 'country/CTE': 'Canton and Enderbury Islands',
 'country/CUB': 'Cuba',
 'country/CUW': 'Curaçao',
 'country/CXR': 'Christmas Island',
 'country/CYM': 'Cayman Islands',
 'country/CYP': 'Cyprus',
 'country/CZE': 'Czech Republic',
 'country/DEU': 'Germany',
 'country/DJI': 'Djibouti',
 'country/DMA': 'Dominica',
 'country/DNK': 'Denmark',
 'country/DOM': 'Dominican Republic',
 'country/DZA': 'Algeria',
 'country/ECU': 'Ecuador',
 'country/EGY': 'Egypt',
 'country/ERI': 'Eritrea',
 'country/ESH': 'Western Sahara',
 'country/ESP': 'Spain',
 'country/EST': 'Estonia',
 'country/ETH': 'Ethiopia',
 'country/FIN': 'Finland',
 'country/FJI': 'Fiji',
 'country/FLK': 'Falkland Islands',
 'country/FRA': 'France',
 'country/FRO': 'Faroe Islands',
 'country/FSM': 'Federated States of Micronesia',
 'country/FXX': 'Metropolitan France',
 'country/GAB': 'Gabon',
 'country/GBR': 'United Kingdom',
 'country/GEO': 'Georgia',
 'country/GGY': 'Guernsey',
 'country/GHA': 'Ghana',
 'country/GIB': 'Gibraltar',
 'country/GIN': 'Guinea',
 'country/GLP': 'Guadeloupe',
 'country/GMB': 'Gambia',
 'country/GNB': 'Guinea-Bissau',
 'country/GNQ': 'Equatorial Guinea',
 'country/GRC': 'Greece',
 'country/GRD': 'Grenada',
 'country/GRL': 'Greenland',
 'country/GTM': 'Guatemala',
 'country/GUF': 'French Guiana',
 'country/GUM': 'Guam',
 'country/GUY': 'Guyana',
 'country/HKG': 'Hong Kong',
 'country/HMD': 'Heard Island and McDonald Islands',
 'country/HND': 'Honduras',
 'country/HRV': 'Croatia',
 'country/HTI': 'Haiti',
 'country/HUN': 'Hungary',
 'country/IDN': 'Indonesia',
 'country/IMN': 'Isle of Man',
 'country/IND': 'India',
 'country/IOT': 'British Indian Ocean Territory',
 'country/IRL': 'Ireland',
 'country/IRN': 'Iran',
 'country/IRQ': 'Iraq',
 'country/ISL': 'Iceland',
 'country/ISR': 'Israel',
 'country/ITA': 'Italy',
 'country/JAM': 'Jamaica',
 'country/JEY': 'Jersey',
 'country/JOR': 'Jordan',
 'country/JPN': 'Japan',
 'country/KAZ': 'Kazakhstan',
 'country/KEN': 'Kenya',
 'country/KGZ': 'Kyrgyzstan',
 'country/KHM': 'Cambodia',
 'country/KIR': 'Kiribati',
 'country/KNA': 'Saint Kitts and Nevis',
 'country/KOR': 'South Korea',
 'country/KWT': 'Kuwait',
 'country/LAO': 'Laos',
 'country/LBN': 'Lebanon',
 'country/LBR': 'Liberia',
 'country/LBY': 'Libya',
 'country/LCA': 'Saint Lucia',
 'country/LIE': 'Liechtenstein',
 'country/LKA': 'Sri Lanka',
 'country/LSO': 'Lesotho',
 'country/LTU': 'Lithuania',
 'country/LUX': 'Luxembourg',
 'country/LVA': 'Latvia',
 'country/MAC': 'Macau',
 'country/MAF': 'Saint Martin',
 'country/MAR': 'Morocco',
 'country/MCO': 'Monaco',
 'country/MDA': 'Moldova',
 'country/MDG': 'Madagascar',
 'country/MDV': 'Maldives',
 'country/MEX': 'Mexico',
 'country/MHL': 'Marshall Islands',
 'country/MKD': 'Macedonia [FYROM]',
 'country/MLI': 'Mali',
 'country/MLT': 'Malta',
 'country/MMR': 'Myanmar',
 'country/MNE': 'Montenegro',
 'country/MNG': 'Mongolia',
 'country/MNP': 'Northern Mariana Islands',
 'country/MOZ': 'Mozambique',
 'country/MRT': 'Mauritania',
 'country/MSR': 'Montserrat',
 'country/MTQ': 'Martinique',
 'country/MUS': 'Mauritius',
 'country/MWI': 'Malawi',
 'country/MYS': 'Malaysia',
 'country/MYT': 'Mayotte',
 'country/NAM': 'Namibia',
 'country/NCL': 'New Caledonia',
 'country/NER': 'Niger',
 'country/NFK': 'Norfolk Island',
 'country/NGA': 'Nigeria',
 'country/NIC': 'Nicaragua',
 'country/NIU': 'Niue',
 'country/NLD': 'Netherlands',
 'country/NOR': 'Norway',
 'country/NPL': 'Nepal',
 'country/NRU': 'Nauru',
 'country/NZL': 'New Zealand',
 'country/OMN': 'Oman',
 'country/PAK': 'Pakistan',
 'country/PAN': 'Panama',
 'country/PCN': 'Pitcairn Islands',
 'country/PER': 'Peru',
 'country/PHL': 'Philippines',
 'country/PLW': 'Palau',
 'country/PNG': 'Papua New Guinea',
 'country/POL': 'Poland',
 'country/PRI': 'Puerto Rico',
 'country/PRK': 'North Korea',
 'country/PRT': 'Portugal',
 'country/PRY': 'Paraguay',
 'country/PSE': 'Palestinian Territories',
 'country/PYF': 'French Polynesia',
 'country/QAT': 'Qatar',
 'country/REU': 'Réunion',
 'country/ROU': 'Romania',
 'country/RUS': 'Russia',
 'country/RWA': 'Rwanda',
 'country/SAU': 'Saudi Arabia',
 'country/SDN': 'Sudan',
 'country/SEN': 'Senegal',
 'country/SGP': 'Singapore',
 'country/SGS': 'South Georgia and the South Sandwich Islands',
 'country/SHN': 'Saint Helena',
 'country/SJM': 'Svalbard and Jan Mayen',
 'country/SLB': 'Solomon Islands',
 'country/SLE': 'Sierra Leone',
 'country/SLV': 'El Salvador',
 'country/SMR': 'San Marino',
 'country/SOM': 'Somalia',
 'country/SPM': 'Saint Pierre and Miquelon',
 'country/SRB': 'Serbia',
 'country/SSD': 'South Sudan',
 'country/STP': 'São Tomé and Príncipe',
 'country/SUR': 'Suriname',
 'country/SVK': 'Slovakia',
 'country/SVN': 'Slovenia',
 'country/SWE': 'Sweden',
 'country/SWZ': 'Eswatini',
 'country/SXM': 'Sint Maarten',
 'country/SYC': 'Seychelles',
 'country/SYR': 'Syria',
 'country/TCA': 'Turks and Caicos Islands',
 'country/TCD': 'Chad',
 'country/TGO': 'Togo',
 'country/THA': 'Thailand',
 'country/TJK': 'Tajikistan',
 'country/TKL': 'Tokelau',
 'country/TKM': 'Turkmenistan',
 'country/TLS': 'East Timor',
 'country/TON': 'Tonga',
 'country/TTO': 'Trinidad and Tobago',
 'country/TUN': 'Tunisia',
 'country/TUR': 'Turkey',
 'country/TUV': 'Tuvalu',
 'country/TWN': 'Taiwan',
 'country/TZA': 'Tanzania',
 'country/UGA': 'Uganda',
 'country/UKR': 'Ukraine',
 'country/UMI': 'U.S. Minor Outlying Islands',
 'country/URY': 'Uruguay',
 'country/USA': 'United States',
 'country/UZB': 'Uzbekistan',
 'country/VAT': 'Vatican City',
 'country/VCT': 'Saint Vincent and the Grenadines',
 'country/VEN': 'Venezuela',
 'country/VGB': 'British Virgin Islands',
 'country/VIR': 'U.S. Virgin Islands',
 'country/VNM': 'Vietnam',
 'country/VUT': 'Vanuatu',
 'country/WLF': 'Wallis and Futuna',
 'country/WSM': 'Samoa',
 'country/XKS': 'Kosovo',
 'country/YEM': 'Yemen',
 'country/YUG': 'Yugoslavia',
 'country/ZAF': 'South Africa',
 'country/ZMB': 'Zambia',
 'country/ZWE': 'Zimbabwe'}

In [ ]:
def get_country_code(country_name, existing_codes):
    try:
        country = pycountry.countries.lookup(country_name)
        return country.alpha_2
    except LookupError:
      #note that there are some counties only exist in datacommon but not in pycountry
        print(country_name)
        code = country_name[:2].upper()
        if code in existing_codes:
            code = (country_name[0] + country_name[-1]).upper()
        return code

def create_country_dataframe(country_ids_data):
    countries = []
    existing_codes = {country.alpha_2 for country in pycountry.countries}

    for dcid, name in country_ids_data.items():
        country_code = get_country_code(name, existing_codes)
        countries.append((country_code, name))
        existing_codes.add(country_code)

    country_df = pd.DataFrame(countries, columns=['CountryCode', 'CountryName'])
    return country_df

country_data = create_country_dataframe(country_ids_data)
country_data

Netherlands Antilles
British Antarctic Territory
Dronning Maud Land
Brunei
Congo [DRC]
Congo [Republic]
Cape Verde
Canton and Enderbury Islands
Falkland Islands
Metropolitan France
Macau
Saint Martin
Macedonia [FYROM]
Pitcairn Islands
Palestinian Territories
Russia
Saint Helena
São Tomé and Príncipe
Sint Maarten
East Timor
Turkey
U.S. Minor Outlying Islands
Vatican City
U.S. Virgin Islands
Kosovo
Yugoslavia

    CountryCode    CountryName
0            AW          Aruba
1            AF    Afghanistan
2            AO         Angola
3            AI       Anguilla
4            AX  Åland Islands
..          ...            ...
251          YE          Yemen
252          YU     Yugoslavia
253          ZA   South Africa
254          ZM         Zambia
255          ZW       Zimbabwe

[256 rows x 2 columns]

In [ ]:
# CO2 = Annual_Emissions_CarbonDioxide_NonBiogenic
# Methane = Annual_Emissions_Methane_NonBiogenic
# Population = Count_Person


def fetch_timelines_data_country():
    # Getting DCIDs for all the countries
    country_ids_data = get_country_ids()

    # Getting the timelines data
    timelines_data = {}
    for key, value in country_ids_data.items():
        try:
            timelines_data[value] = {'Population': round(dc.get_stat_all([key], ['Count_Person'])[key]['Count_Person']['sourceSeries'][0]['val']['2022'], 2)}
        except:
            timelines_data[value] = {'Population': 0.00}
        try:
            timelines_data[value].update({'CO2': round(dc.get_stat_all([key], ['Annual_Emissions_CarbonDioxide_NonBiogenic'])[key]['Annual_Emissions_CarbonDioxide_NonBiogenic']['sourceSeries'][0]['val']['2021'], 2)})
        except:
            timelines_data[value].update({'CO2': 0.00})
        try:
            timelines_data[value].update({'Methane': round(dc.get_stat_all([key], ['Annual_Emissions_Methane_NonBiogenic'])[key]['Annual_Emissions_Methane_NonBiogenic']['sourceSeries'][0]['val']['2021'], 2)})
        except:
            timelines_data[value]. update({'Methane': 0.00})

    # Creating the dataframe
    normalized_data = []
    for country, values in timelines_data.items():
        entry = {'CountryName': country}
        entry.update(values)
        normalized_data.append(entry)
    dataframe = pd.DataFrame(normalized_data)

    return dataframe

timelines_country = fetch_timelines_data_country()
timelines_country

       CountryName  Population  CO2  Methane
0            Aruba   106445.00 0.00     0.00
1      Afghanistan 41128771.00 0.00     0.00
2           Angola 35588987.00 0.00     0.00
3         Anguilla        0.00 0.00     0.00
4    Åland Islands        0.00 0.00     0.00
..             ...         ...  ...      ...
251          Yemen 33696614.00 0.00     0.00
252     Yugoslavia        0.00 0.00     0.00
253   South Africa 59893885.00 0.00     0.00
254         Zambia 20017675.00 0.00     0.00
255       Zimbabwe 16320537.00 0.00     0.00

[256 rows x 4 columns]

combined

In [ ]:
# Country
dc.get_stat_all(['country/USA'], ['Annual_Amount_Emissions_CarbonDioxide'])['country/USA']['Annual_Amount_Emissions_CarbonDioxide']

{'sourceSeries': [{'val': {'2011': 5128105384,
    '1978': 4771142682,
    '2020': 4257738096,
    '1972': 4527984118,
    '2017': 4761301727,
    '1999': 5563819024,
    '1989': 4904547626,
    '1975': 4355839181,
    '1993': 4952699132,
    '1994': 5024064992,
    '2001': 5702105773,
    '1966': 3547095488,
    '1968': 3898241195,
    '2010': 5352049740,
    '1970': 4231974784,
    '1963': 3085190502,
    '1961': 2832097916,
    '1973': 4691090844,
    '1976': 4616828588,
    '1986': 4478048562,
    '1997': 5498830887,
    '2003': 5610687172,
    '1984': 4485577869,
    '1988': 4842013205,
    '1992': 4837695301,
    '2014': 5046564428,
    '2007': 5686667534,
    '2006': 5602396200,
    '1964': 3196050810,
    '2004': 5688704740,
    '1971': 4289035482,
    '2002': 5545413879,
    '1960': 2813809267,
    '2018': 4909996024,
    '1985': 4514313221,
    '2005': 5703154482,
    '2000': 5729820336,
    '1987': 4633016119,
    '1991': 4765689535,
    '2016': 4838476243,
    '2008': 5512449220,
    '1995': 5073840232,
    '1983': 4294487954,
    '2019': 4744449220,
    '1962': 2951022644,
    '1998': 5545388048,
    '1969': 4038171997,
    '1981': 4533920776,
    '1980': 4595789109,
    '2021': 4483810505,
    '1977': 4781620648,
    '1996': 5230479902,
    '1974': 4539981890,
    '2013': 5038524675,
    '2015': 4928610664,
    '1990': 4803002330,
    '1979': 4800310290,
    '1982': 4321082520,
    '2009': 5120626218,
    '1965': 3358654879,
    '2012': 4902939710,
    '1967': 3684656198},
   'importName': 'OECD_Air_GHG_emissions',
   'provenanceDomain': 'oecd.org',
   'unit': 'MetricTon',
   'provenanceUrl': 'https://data.oecd.org/air/air-and-ghg-emissions.htm'}]}

In [ ]:
sum(timelines_df['Methane'])

179803997.54000002

# Code for Priyanka

In [ ]:
def get_county_ids():
  # Getting the county  dcids
  county_dcids = {}
  county_names = []
  for key,value in state_ids_data.items():
    county_dcids.update(dc.get_places_in([key], 'County'))
  # Getting the names of the county
    county_names = {}
  for key,value in county_dcids.items():
    for county_id in value:
      county_names[county_id] = dc.get_property_values([county_id], 'name')[county_id][0]
  return county_names

In [ ]:
county_ids_data = get_county_ids()
county_ids_data

NameError: name 'state_ids_data' is not defined

Code updated by Priyanka for Population data of all counties

In [ ]:
population_data_all_county = {}
for key,value in county_ids_data.items():
    try:
        #population_data_all_county[value] = {str(1970): dc.get_stat_all([key], ['Count_Person'])[key]['Count_Person']['sourceSeries'][0]['val']['1970']}
        stats = dc.get_stat_all([key], ['Count_Person'])[key]['Count_Person']['sourceSeries'][0]['val']
        population_data_all_county[value] = {str(year): stats.get(str(year), 0) for year in range(1970, 2023)}
    except:
        population_data_all_county[value] = {str(1970): 0}
        population_data_all_county[value] = {str(year): 0 for year in range(1970, 2023)}
    for year in range(1971,2023):
        try:
            population_data_all_county[value] = {str(year): stats.get(str(year), 0) for year in range(1970, 2023)}
            #population_data_all_county[value].update({str(year): dc.get_stat_all([key], ['Count_Person'])[key]['Count_Person']['sourceSeries'][0]['val'][str(year)]})
        except:
            #population_data_all_county[value].update({str(year): 0})
            population_data_all_county[value] = {str(year): 0 for year in range(1970, 2023)}

# for key, value in county_ids_data.items():
#     try:
#         stats = dc.get_stat_all([key], ['Count_Person'])[key]['Count_Person']['sourceSeries'][0]['val']
#         population_data_all_county[value] = {str(year): stats.get(str(year), 0) for year in range(1970, 2023)}
#     except:
#         population_data_all_county[value] = {str(year): 0 for year in range(1970, 2023)}

In [ ]:
population_data_all_county

In [ ]:
def County_Data_to_Dataframe(data):
  # Adding County as a Column and Converting the data to dataframe
  normalized_data = []
  for county, values in data.items():
      entry = {'CountyName': county}
      entry.update(values)
      normalized_data.append(entry)
  dataframe = pd.DataFrame(normalized_data)


  return dataframe

In [ ]:
population_dataframe_all_county = County_Data_to_Dataframe(population_data_all_county)
population_dataframe_all_county.head()

In [ ]:
population_dataframe_all_county

In [ ]:
population_dataframe_all_county.to_csv('County_data_all_years.csv',index=False)

In [ ]:
pd.read_csv('County_data_all_years.csv')